services:
  - type: web
    name: second-hand-platform
    env: node
    region: frankfurt
    plan: starter
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
